package com.haufelexware.report.junit;

import com.haufelexware.report.junit.dom.JUnitTestSuite;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.InputStream;

/**
 * This parser will parse a given stream into a JUnit-DOM.
 *
 * Please note that the junit-xml-report is not generated by JUnit itself. Apache Ant was
 * the first build tool to convert the JUnit test results into a XML file. Apache Maven
 * and Gradle stick to this schema.
 */
public class JUnitReportParser {

	private final Unmarshaller unmarshaller;

	public JUnitReportParser() {
		try {
			unmarshaller = JAXBContext.newInstance(JUnitTestSuite.class).createUnmarshaller();
		} catch (JAXBException e) {
			throw new IllegalArgumentException("Could not initialize Unmarshaller", e);
		}
	}

	public JUnitTestSuite parseFrom(InputStream stream) throws JAXBException {
		return (JUnitTestSuite)unmarshaller.unmarshal(stream);
	}
}
